<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.3.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.19" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ReportViewerForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ReportViewerForm.Designer.vb">
      <DependentUpon>ReportViewerForm.vb</DependentUpon>
    </Compile>
    <EmbeddedResource Include="EnrollmentReport.rdlc" />
    <None Include="EnrollmentData.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>EnrollmentData.Designer.vb</LastGenOutput>
    </None>
    <Compile Update="EnrollmentData.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EnrollmentData.xsd</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>